export const actionTypes = {

  TRACKS_START_FETCHING: 'TRACKS_START_FETCHING',
  TRACKS_FETCHED: 'TRACKS_FETCHED',
  TRACKS_FETCH_ERROR: 'TRACKS_FETCH_ERROR',


  FETCH_SINGLE_TRACK: 'FETCH_SINGLE_TRACK',
  PLAY_THE_TRACK: 'PLAY_THE_TRACK',
  PAUSE_THE_TRACK: 'PAUSE_THE_TRACK',
  STOP_THE_TRACK: 'STOP_THE_TRACK',

  PLAY_ALL_TRACKS: 'PLAY_ALL_TRACKS',


  SELECT_COLOUR_MODE: 'SELECT_COLOUR_MODE',


}